name: 05-actions@-Pipeline
on: push
jobs:
    Job-1-flask-job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v7

            - name: Build Docker image
              run: docker build -t cicd-flask-app:version01 .

            - name: Run Container
              run: docker run -d -p 5000:5000 --name  cicd-flask-container cicd-flask-app:version01 

            - name: Debugging the container
              run: |
                docker ps -a
                docker logs cicd-flask-container

            - name: Smoke Test
              run: |
                sleep 10
                curl http://localhost:5000/health
        