name: 07 - Filter Workflow Trigger Demo
on:
  push:
    branches:
      - develop
      - "feature/*"
    paths:
      - "app1/**"
      - "docker/**"
      - ".github/workflows/**"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - ready_for_review
    branches:
      - main

jobs:
  validation-job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print the workflow context
        run: |
          echo "Workflow is triggered successfully"
          echo "Event type: ${GITHUB_EVENT_NAME}"
          echo "Branch: $GITHUB_REF_NAME"
          echo "SHA: ${GITHUB_SHA}"
          echo "Owner: ${GITHUB_REPOSITORY_OWNER}"